language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    # php8 is not supported yet
    #- nightly

env:
    matrix:
        - DEPENDENCIES=high
        - DEPENDENCIES=low
    global:
        - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-ansi --no-progress --no-suggest"

matrix:
    fast_finish: true

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then COMPOSER_MEMORY_LIMIT=2G travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then COMPOSER_MEMORY_LIMIT=2G travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

cache:
    directories:
        - $HOME/.composer/cache
